blank_issues_enabled: true
contact_links:
  - name: Stardance Help
    url: https://hackclub.enterprise.slack.com/archives/C0AP0NMSP3P
    about: Having issues with the platform, ask the support scouts on slack!
